name: Update Submodules

on:
  push:
  workflow_dispatch:

jobs:
  update_submodules:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
      with:
        submodules: 'recursive'
    - name: Update Submodules
      run: |
        git submodule init
        git submodule update
      env:
        SSH_AUTH_SOCK: /tmp/ssh_agent.sock
